# -*- coding: utf-8 -*-
"""Tomatoe Detection v2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xgeKXDTnmKj6NOBrAq3LwUpYZwRN9gTn
"""

!pip install ultralytics

import os
import zipfile
from google.colab import files

from google.colab import files

uploaded = files.upload()

import zipfile
import os

zip_path = "/content/Tomato detection v2.zip"
extract_path = "/content/tomato_dataset"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print(os.listdir(extract_path))

import os
import shutil
import random

source = "/content/tomato_dataset/obj_train_data"
dataset = "/content/tomato_yolo"

# Create folders
os.makedirs(f"{dataset}/images/train", exist_ok=True)
os.makedirs(f"{dataset}/images/val", exist_ok=True)
os.makedirs(f"{dataset}/labels/train", exist_ok=True)
os.makedirs(f"{dataset}/labels/val", exist_ok=True)

# Find images
images = [
    f for f in os.listdir(source)
    if f.lower().endswith((".jpg", ".jpeg", ".png"))
]

# Use the same 80/20 split
random.seed(42)
random.shuffle(images)

split_index = int(len(images) * 0.8)

train_images = images[:split_index]
val_images = images[split_index:]

# Copy training images + labels
for image in train_images:
    label = os.path.splitext(image)[0] + ".txt"

    shutil.copy(
        os.path.join(source, image),
        os.path.join(dataset, "images/train", image)
    )

    shutil.copy(
        os.path.join(source, label),
        os.path.join(dataset, "labels/train", label)
    )

# Copy validation images + labels
for image in val_images:
    label = os.path.splitext(image)[0] + ".txt"

    shutil.copy(
        os.path.join(source, image),
        os.path.join(dataset, "images/val", image)
    )

    shutil.copy(
        os.path.join(source, label),
        os.path.join(dataset, "labels/val", label)
    )

print("Training images:", len(train_images))
print("Validation images:", len(val_images))
print("Training:", train_images)
print("Validation:", val_images)

yaml_content = """
path: /content/tomato_yolo

train: images/train
val: images/val

nc: 1
names:
  0: Tomato
"""

with open("/content/tomato_yolo/data.yaml", "w") as f:
    f.write(yaml_content)

print("data.yaml created successfully!")

!pip install -q ultralytics

from ultralytics import YOLO

print("Ultralytics is ready!")

from ultralytics import YOLO

model = YOLO("yolo11n.pt")

results = model.train(
    data="/content/tomato_yolo/data.yaml",
    epochs=50,
    imgsz=640,
    batch=4
    )

from ultralytics import YOLO

model = YOLO("/content/runs/detect/train/weights/best.pt")

from google.colab import files

uploaded = files.upload()

results = model.predict(
    source="/content/97.jpg",
    conf=0.3,
    verbose=True
)[0]

print("Tomatoes detected:", len(results.boxes))

for i, conf in enumerate(results.boxes.conf.tolist(), 1):
    print(f"Tomato {i}: {conf*100:.1f}%")

import matplotlib.pyplot as plt

# 1. Run prediction on image 97
results = model.predict(
    source="/content/97.jpg",
    conf=0.30,
    verbose=True
)[0]

# 2. Print summary and confidence scores
print("Tomatoes detected:", len(results.boxes))

for i, conf in enumerate(results.boxes.conf.tolist(), 1):
    print(f"Tomato {i}: {conf*100:.1f}%")

# 3. Plot and display the annotated image
annotated = results.plot()

plt.figure(figsize=(12, 8))
plt.imshow(annotated[:, :, ::-1]) # Convert BGR to RGB for Matplotlib
plt.axis("off")
plt.show()