# -*- coding: utf-8 -*-
"""Tomatoe Detection

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/176ibNbJT0pifLLMPOGQ7Ew0jGS31xop8
"""

!pip install ultralytics

import zipfile
import os

zip_path = "/content/Tomato detection v2.zip"
extract_path = "/content/tomato_dataset"

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Dataset extracted successfully!")
print(os.listdir(extract_path))

import os

data_folder = "/content/tomato_dataset/obj_train_data"

files = os.listdir(data_folder)

images = [f for f in files if f.lower().endswith((".jpg", ".jpeg", ".png"))]
labels = [f for f in files if f.lower().endswith(".txt")]

print("Number of images:", len(images))
print("Number of labels:", len(labels))

print("\nImages:")
print(images)

print("\nLabels:")
print(labels)

import os

data_folder = "/content/tomato_dataset/obj_train_data"

for filename in sorted(os.listdir(data_folder)):
    if filename.endswith(".txt"):
        path = os.path.join(data_folder, filename)
        with open(path, "r") as f:
            lines = f.readlines()

        print(f"\n{filename}: {len(lines)} tomato(s)")
        print("First annotation:", lines[0].strip())

from google.colab import files

uploaded = files.upload()

import zipfile
import os

zip_path = "/content/Tomato detection v2.zip"
extract_path = "/content/tomato_dataset"

with zipfile.ZipFile(zip_path, "r") as zip_ref:
    zip_ref.extractall(extract_path)

print(os.listdir(extract_path))

import os
import shutil
import random

source = "/content/tomato_dataset/obj_train_data"
dataset = "/content/tomato_yolo"

# Create folders
os.makedirs(f"{dataset}/images/train", exist_ok=True)
os.makedirs(f"{dataset}/images/val", exist_ok=True)
os.makedirs(f"{dataset}/labels/train", exist_ok=True)
os.makedirs(f"{dataset}/labels/val", exist_ok=True)

# Find images
images = [
    f for f in os.listdir(source)
    if f.lower().endswith((".jpg", ".jpeg", ".png"))
]

# Use the same 80/20 split
random.seed(42)
random.shuffle(images)

split_index = int(len(images) * 0.8)

train_images = images[:split_index]
val_images = images[split_index:]

# Copy training images + labels
for image in train_images:
    label = os.path.splitext(image)[0] + ".txt"

    shutil.copy(
        os.path.join(source, image),
        os.path.join(dataset, "images/train", image)
    )

    shutil.copy(
        os.path.join(source, label),
        os.path.join(dataset, "labels/train", label)
    )

# Copy validation images + labels
for image in val_images:
    label = os.path.splitext(image)[0] + ".txt"

    shutil.copy(
        os.path.join(source, image),
        os.path.join(dataset, "images/val", image)
    )

    shutil.copy(
        os.path.join(source, label),
        os.path.join(dataset, "labels/val", label)
    )

print("Training images:", len(train_images))
print("Validation images:", len(val_images))
print("Training:", train_images)
print("Validation:", val_images)

yaml_content = """
path: /content/tomato_yolo

train: images/train
val: images/val

nc: 1
names:
  0: Tomato
"""

with open("/content/tomato_yolo/data.yaml", "w") as f:
    f.write(yaml_content)

print("data.yaml created successfully!")

!pip install -q ultralytics

from ultralytics import YOLO

print("Ultralytics is ready!")

from PIL import Image, ImageDraw
import os

image_path = "/content/tomato_yolo/images/train/0019.jpg"
label_path = "/content/tomato_yolo/labels/train/0019.txt"

image = Image.open(image_path).convert("RGB")
draw = ImageDraw.Draw(image)

img_w, img_h = image.size

with open(label_path, "r") as f:
    for line in f:
        values = line.strip().split()

        x_center = float(values[1])
        y_center = float(values[2])
        width = float(values[3])
        height = float(values[4])

        x1 = (x_center - width / 2) * img_w
        y1 = (y_center - height / 2) * img_h
        x2 = (x_center + width / 2) * img_w
        y2 = (y_center + height / 2) * img_h

        draw.rectangle([x1, y1, x2, y2], outline="red", width=3)
        draw.text((x1, y1), "Tomato", fill="red")

display(image)

from ultralytics import YOLO

model = YOLO("yolo11n.pt")

results = model.train(
    data="/content/tomato_yolo/data.yaml",
    epochs=50,
    imgsz=640,
    batch=4
)

from ultralytics import YOLO

model = YOLO("/content/runs/detect/train/weights/best.pt")

from google.colab import files

uploaded = files.upload()

from google.colab import files

uploaded = files.upload()

import os

print(os.listdir("/content"))

import os

print(os.listdir("/content"))

result22 = model.predict(
    source="/content/0022.jpg",
    conf=0.3,
    verbose=True
)[0]

print("Tomatoes detected:", len(result22.boxes))

for i, conf in enumerate(result22.boxes.conf.tolist(), 1):
    print(f"Tomato {i}: {conf*100:.1f}%")

import matplotlib.pyplot as plt

annotated = result22.plot()

plt.figure(figsize=(12, 8))
plt.imshow(annotated[:, :, ::-1])
plt.axis("off")
plt.show()

# Run prediction with stricter NMS (iou=0.4) and confidence threshold
results = model.predict(source="/content/0022.jpg", iou=0.4, conf=0.3)

# Visualize the updated results
annotated = results[0].plot()
plt.imshow(annotated[:, :, ::-1])
plt.axis("off")
plt.show()

results = model.predict(
    source="/content/0016.jpg",
    conf=0.15,
    save=True
)

from google.colab import files

uploaded = files.upload()

import os

print(os.listdir("/content"))

result19 = model.predict(
    source="/content/0019.jpg",
    conf=0.07,
    verbose=True
)[0]

print("Tomatoes detected:", len(result19.boxes))

for i, conf in enumerate(result19.boxes.conf.tolist(), 1):
    print(f"Tomato {i}: {conf*100:.1f}%")

import matplotlib.pyplot as plt

annotated = result19.plot()

plt.figure(figsize=(12, 8))
plt.imshow(annotated[:, :, ::-1])
plt.axis("off")
plt.show()